//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket.com.bd_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Customer
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        public string email { get; set; }
        //[Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        //[Required(ErrorMessage = "Password is Required")]
        //[Compare("password", ErrorMessage = "The Password and Confirm Password does not match")]
        public string confirmpassword { get; set; }
        [Required(ErrorMessage = "Address is Required")]
        public string address { get; set; }
        [Required(ErrorMessage = "NID is Required")]
        public string nid { get; set; }
        [Required(ErrorMessage = "Phone Number is Required")] 
        public string phone { get; set; }
        [Required(ErrorMessage = "N.B: You Have To 100TK To The Customer Account")]
        public decimal balance { get; set; }
    }
}
